CREATE TABLE
    IF NOT EXISTS users (
        user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username TEXT UNIQUE NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL,
        bio TEXT NOT NULL DEFAULT '',
        image TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now ()
    );

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);